[tool.poetry]
name = "plotly-dynamic-resampling"
version = "0.1.0"
description = ""
authors = ["Jonas Van Der Donckt", "Emiel Deprost", "Jeroen Van Der Donckt"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
jupyter-dash = "^0.4.0"
dash-bootstrap-components = "^0.13.1"
lttbc = "^0.2.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.2.0"
numpy = "^1.21.2"
pandas = "^1.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
