[tool.poetry]
name = "plotly-dynamic-resampling"
version = "0.1.0"
description = ""
authors = ["Emiel Deprost <emiel.deprost@ugent.be>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
